wandb_version: 1

output_dir:
  desc: null
  value: ''
seq_length:
  desc: null
  value: 512
batch_size:
  desc: null
  value: 2
gradient_accumulation_steps:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 2.0e-05
epochs:
  desc: null
  value: 1
warmup_steps:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718004555
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.1
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
